[build]
builder = "nixpacks"
buildCommand = "cd apps/api && npx prisma generate && npx tsc"

[deploy]
startCommand = "cd apps/api && node dist/index.js"
preDeployCommand = "cd apps/api && npx prisma db push --skip-generate"
