[build]
builder = "nixpacks"

[build.env]
NIXPACKS_INSTALL_CMD = "npm install"
NIXPACKS_BUILD_CMD = "npx prisma db push --schema=apps/api/prisma/schema.prisma && npm run build --workspace=apps/api"

[deploy]
startCommand = "npm run start --workspace=apps/api"
